//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicClosetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public string Type { get; set; }
        public string Color { get; set; }
        public int CategoryID { get; set; }
        public int SeasonID { get; set; }
        public int OccassionsID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Season Season { get; set; }
        public virtual Occassion Occassion { get; set; }
    }
}
